# Generated by Django 2.2.16 on 2022-01-02 06:24

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='tags_slug'),
        ),
    ]
