# Generated by Django 2.2.16 on 2022-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220102_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.CharField(default='Текстовое описание', max_length=200),
        ),
    ]
