# Generated by Django 2.2.16 on 2022-01-03 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_recipes_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='units',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ready_time',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='title',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.TextField(default='Kg'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(default='Food', max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='text',
            field=models.TextField(default='Text'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ingredients'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'author')},
            },
        ),
    ]
