# Generated by Django 2.2.16 on 2022-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220103_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
