# Generated by Django 2.2.16 on 2022-01-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220106_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='tag',
            new_name='tags',
        ),
    ]
