# Generated by Django 2.2.16 on 2022-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220107_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='app.Tags'),
        ),
    ]
