version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    network_mode: host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
